server:
  port: 8080
  servlet:
    context-path: /book_review

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/book_review"
    username: root
    password: soihoang2904
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true